### PR TITLE
Add support for krotodc by adding the `krotodc-grpc` flag

### PR DESCRIPTION
**Pull request by mscheong01**
Updates were requested in https://github.com/line/armeria/pull/5092#discussion_r1281428694

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks, @mscheong01! I wish krotoDC will become a de-facto standard gRPC stub for Kotlin. 😉

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Review by trustin — APPROVED** [review]
:+1: Thanks, @mscheong01 :bow:

**Pull request merged**
