### PR TITLE
Use modern features of Gradle instead of custom scripts where possible

### PR DESCRIPTION
**Pull request by anuraaga**
Copied from https://github.com/line/armeria/pull/2420

### CODE REVIEW

**Comment by trustin** [comment]
Already approved at https://github.com/line/armeria/pull/2420 Thanks again, @anuraaga !

**Comment by minwoox** [comment]
I realized that maven publish does not handle `runtime` configuration properly.
https://discuss.gradle.org/t/maven-publish-plugin-generated-pom-making-dependency-scope-runtime/7494

It's converted to compile scope when the POM file is created.
So my question is:
Should we revert to use `pom.withXml` to create the POM file correctly?
Or should we encourage people to use `api`, `implemenation` and `runtimeOnly` because `compile` and `runtime` will be removed from Gradle 7.0.
/cc @anuraaga, @trustin and @ikhoon

**Comment by minwoox** [comment]
I also found out that there's a possibility that the dependency in `<exclusion>` might not be excluded.
My case is that
- I want to exclude `foo` dependency from Guava.
- `line-common` has Guava dependency.
- 'line-other1', 'line-other2', 'line-other3' have `line-common` dependency.

In this case we should exclude `foo` dependency from all `Guava`, `line-common`, `line-other1` ...

**Comment by anuraaga** [comment]
> Or should we encourage people to use api, implemenation and runtimeOnly because compile and runtime will be removed from Gradle 7.0.

Definitely

> In this case we should exclude foo dependency from all Guava, line-common, line-other1 ...

Are you saying that `foo` is excluded from guava transitive dependency of `line-common`, but for some reason is included in `line-other`, despite it having been excluded from transitive dependencies of `line-common`? This seems surprising, the POM looks fine for exclusions

https://repo1.maven.org/maven2/com/linecorp/armeria/armeria-grpc/1.6.0/armeria-grpc-1.6.0.pom

**Comment by minwoox** [comment]
> Are you saying that foo is excluded from guava transitive dependency of line-common, but for some reason is included in line-other, despite it having been excluded from transitive dependencies of line-common?

Yes, that's what I'm seeing. Let me try that once more to make sure.

**Comment by trustin** [comment]
> Or should we encourage people to use api, implemenation and runtimeOnly because compile and runtime will be removed from Gradle 7.0.

+1

It'd be nice if we can still support `compile` and `runtime` but we could stop supporting them if it's not viable to support them. If we stop supporting them, would it be possible to fail the build if a user defined a dependency with the deprecated configurations?

**Comment by minwoox** [comment]
> but for some reason is included in line-other, despite it having been excluded from transitive dependencies of line-common

Please, forget about it. 😅  I guess I was doing something wrong.

> If we stop supporting them, would it be possible to fail the build if a user defined a dependency with the deprecated configurations?"

Yeah, I think so. Let's do that. 😄

**Pull request merged**
