### PR TITLE
Fix `ktlintCheck` task

### PR DESCRIPTION
**Pull request by heowc**
Motivation:

The task I mentioned has two problems. 
The task does not work under `lint` task. It also works when adding settings with `noLint`.
(Relates https://github.com/line/armeria/pull/3702)

Modifications:

- Fix gradle script (`kotlin.gradle`)

Result:

- Fixes https://github.com/line/armeria/pull/3702

### CODE REVIEW

**Comment by ikhoon** [comment]
https://github.com/line/armeria/pull/3702/files#diff-707eab3a0d284369fa87de5f0348e94309f296521cbff55dd33c3037d269864cR37 
By the way, this line does not exist in this PR. 🤔

**Comment by heowc** [comment]
> https://github.com/line/armeria/pull/3702/files#diff-707eab3a0d284369fa87de5f0348e94309f296521cbff55dd33c3037d269864cR37
> By the way, this line does not exist in this PR. 🤔

Oops.... 😭

**Comment by trustin** [comment]
I pushed a follow-up commit to `master`

**Comment by heowc** [comment]
Thank you!! :)

**Pull request merged**
