### PR TITLE
Print git stdout when it fails with nothing on stderr

### LINKED ISSUE #144: Also show stdout of git command when it fails
We have a issue where release plugin fails to `git -m some_message` with error code = 1
And stderr is empty
I suspect it's printing something to sdtout too

### PR DESCRIPTION
**Pull request by mauhiz**
Closes #144

### CODE REVIEW

**Review by trustin — APPROVED** [review]
Thanks, @mauhiz!

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by ikhoon — APPROVED** [review]
👍

**Comment by trustin** [comment]
Sorry for a belated merge, @mauhiz. Thanks a lot for your PR 🙇

**Pull request merged**
