### PR TITLE
Add Thrift 0.16 compiler binaries for Windows and Linux and fix compiler extensions

### PR DESCRIPTION
**Pull request by trustin**
- Added the Thrift 0.16 compiler binaries for Windows and Linux
- Appended `.exe` to all Windows binaries
- Removed the 'executable' attributes from all Windows binaries
- Changed the default Thrift compiiler version from 0.15 to 0.16

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]

**Comment by trustin** [comment]
Let me build the binary for Linux as well.

**Comment by trustin** [comment]
Added the Linux binary and bumped the default compiler version from 0.15 to 0.16.

**Review by jrhee17 — APPROVED** [review]
nit; we could also update the `README` to specify the correct default version

https://github.com/line/gradle-scripts/blob/07b526a012b4c2f779988babd29d3312510e19d9/README.md?plain=1#L401

Otherwise, looks good to me! Thanks 🙇

**Comment by trustin** [comment]
@jrhee17 Thanks for pointing that out. Pushed a fix.

**Pull request merged**
